services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: triagemate-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: triagemate-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"     # INTERNAL (docker network)
      - "29092:29092"   # EXTERNAL (host)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Dual listener
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Single node safe config
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  ingest:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: triagemate-ingest
    depends_on:
      - kafka
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - m2-cache:/root/.m2
    command: ["mvn", "-pl", "triagemate-ingest", "spring-boot:run"]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"

  triage:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: triagemate-triage
    depends_on:
      - kafka
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - m2-cache:/root/.m2
    command: ["mvn", "-pl", "triagemate-triage", "spring-boot:run"]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8082:8082"

  postgres:
    image: postgres:16
    container_name: triagemate-postgres
    environment:
      POSTGRES_DB: triagemate
      POSTGRES_USER: triagemate
      POSTGRES_PASSWORD: triagemate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  m2-cache:
  postgres_data: