spring:
  application:
    name: triagemate-triage

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      fail-fast: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: triagemate-triage
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest

    listener:
      concurrency: 3

    properties:
      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

      spring.json.trusted.packages: com.triagemate.contracts.*
      spring.json.use.type.headers: false
      spring.json.value.default.type: com.triagemate.contracts.events.EventEnvelope

server:
  port: 8082

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%X{requestId}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.apache.catalina: WARN
    org.apache.coyote: WARN
    org.hibernate.validator: WARN

triagemate:
  kafka:
    topics:
      input-received: triagemate.ingest.input-received.v1
      decision-made: triagemate.triage.decision-made.v1
    consumer:
      group-id: triagemate-triage
      retry:
        backoff-ms: 1000
        max-retries: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info

